---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    project: booksapp
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mysql
    project: booksapp
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
      project: booksapp
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        app: mysql
        project: booksapp
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: booksapp_production
        - name: MYSQL_USER
          value: booksapp
        - name: MYSQL_PASSWORD
          value: booksapp
        - name: MYSQL_INITDB_SKIP_TZINFO
          value: "1"
        image: mysql:5.6
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        resources: {}
status: {}
---
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  labels:
    app: mysql-init
    project: booksapp
  name: mysql-init
spec:
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        app: mysql-init
        project: booksapp
      name: mysql-init
    spec:
      containers:
      - args:
        - -c
        - |
          set -e
          bundle exec rake db:ready
          bundle exec rake db:migrate
          bundle exec rake db:seed
        command:
        - /bin/sh
        env:
        - name: DATABASE_URL
          value: mysql2://booksapp:booksapp@mysql:3306/booksapp_production
        image: buoyantio/booksapp:v0.0.3
        name: mysql-init
        resources: {}
      restartPolicy: OnFailure
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
    project: booksapp
spec:
  selector:
    app: webapp
  type: LoadBalancer
  ports:
  - name: service
    port: 7000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webapp
    project: booksapp
  name: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
      project: booksapp
  strategy: {}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        app: webapp
        project: booksapp
    spec:
      containers:
      - args:
        - prod:webapp
        env:
        - name: DATABASE_URL
          value: mysql2://booksapp:booksapp@mysql:3306/booksapp_production
        - name: AUTHORS_SITE
          value: http://authors:7001
        - name: BOOKS_SITE
          value: http://books:7002
        image: buoyantio/booksapp:v0.0.3
        name: service
        ports:
        - containerPort: 7000
          name: service
        readinessProbe:
          httpGet:
            path: /ping
            port: 7000
        resources: {}
      dnsPolicy: ClusterFirst
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: authors
  labels:
    app: authors
    project: booksapp
spec:
  selector:
    app: authors
  clusterIP: None
  ports:
  - name: service
    port: 7001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: authors
    project: booksapp
  name: authors
spec:
  replicas: 3
  selector:
    matchLabels:
      app: authors
      project: booksapp
  strategy: {}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        app: authors
        project: booksapp
    spec:
      containers:
      - args:
        - prod:authors
        env:
        - name: DATABASE_URL
          value: mysql2://booksapp:booksapp@mysql:3306/booksapp_production
        - name: BOOKS_SITE
          value: http://books:7002
        image: buoyantio/booksapp:v0.0.3
        name: service
        ports:
        - containerPort: 7001
          name: service
        readinessProbe:
          httpGet:
            path: /ping
            port: 7001
        resources: {}
      dnsPolicy: ClusterFirst
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: books
  labels:
    app: books
    project: booksapp
spec:
  selector:
    app: books
  clusterIP: None
  ports:
  - name: service
    port: 7002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: books
    project: booksapp
  name: books
spec:
  replicas: 3
  selector:
    matchLabels:
      app: books
      project: booksapp
  strategy: {}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        app: books
        project: booksapp
    spec:
      containers:
      - args:
        - prod:books
        env:
        - name: DATABASE_URL
          value: mysql2://booksapp:booksapp@mysql:3306/booksapp_production
        - name: AUTHORS_SITE
          value: http://authors:7001
        image: buoyantio/booksapp:v0.0.3
        name: service
        ports:
        - containerPort: 7002
          name: service
        readinessProbe:
          httpGet:
            path: /ping
            port: 7002
        resources: {}
      dnsPolicy: ClusterFirst
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: traffic
    project: booksapp
  name: traffic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic
      project: booksapp
  strategy: {}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        app: traffic
        project: booksapp
    spec:
      containers:
      - args:
        - webapp:7000
        image: buoyantio/booksapp-traffic:v0.0.3
        name: traffic
        resources: {}
      dnsPolicy: ClusterFirst
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: authors-clone
  labels:
    app: authors-clone
    project: booksapp
spec:
  selector:
    app: authors-clone
  clusterIP: None
  ports:
  - name: service
    port: 7009
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: authors-clone
    project: booksapp
  name: authors-clone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: authors-clone
      project: booksapp
  strategy: {}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        app: authors-clone
        project: booksapp
    spec:
      containers:
      - args:
        - prod:authors
        env:
        - name: DATABASE_URL
          value: mysql2://booksapp:booksapp@mysql:3306/booksapp_production
        - name: BOOKS_SITE
          value: http://books:7002
        image: buoyantio/booksapp:v0.0.3
        name: service
        ports:
        - containerPort: 7009
          name: service
        readinessProbe:
          httpGet:
            path: /ping
            port: 7001
        resources: {}
      dnsPolicy: ClusterFirst
status: {}
---
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: authors-split
spec:
  service: authors
  backends:
  - service: authors
    weight: 500m
  - service: authors-clone
    weight: 500m
---
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: webapp-split
spec:
  service: webapp
  backends:
  - service: webapp
    weight: 1000m
  - service: webapp-clone
    weight: 0m
---
